# Amazon summary data
BEGINNING_BALANCE_SUBTOTAL = 'Beginning Balance Subtotal'
ORDERS_SUBTOTAL = 'Orders Subtotal'
REFUNDS_SUBTOTAL = 'Refunds Subtotal'
SHIPPING_SERVICES_SUBTOTAL = 'Shipping Services Subtotal'
TOTAL_BALANCE = 'Total Balance'
UNAVAILABLE_BALANCE = 'Unavailable Balance'
TRANSFER_AMOUNT = 'Transfer Amount'

AMAZON_SUMMARY_DATA_TYPES = [BEGINNING_BALANCE_SUBTOTAL, ORDERS_SUBTOTAL, REFUNDS_SUBTOTAL, SHIPPING_SERVICES_SUBTOTAL, TOTAL_BALANCE, UNAVAILABLE_BALANCE, TRANSFER_AMOUNT]